# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtx < Formula
  desc ""
  homepage "https://github.com/rajrohanyadav/dtx"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.4/dtx_Darwin_x86_64.tar.gz"
      sha256 "47e3659f0c80070edc9b2bba498917f92f25e84b9d85c1d6f452968b5b2922af"

      def install
        bin.install "dtx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.4/dtx_Darwin_arm64.tar.gz"
      sha256 "a26e84b364174d11f8dc949c74ce95a400c0b001db2ebd0422e1532455d6e7ce"

      def install
        bin.install "dtx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.4/dtx_Linux_x86_64.tar.gz"
      sha256 "eb2570c2d4433e6fca4a32e9327dad5ded4d8e05e42c655e5a762a89dd1baf73"

      def install
        bin.install "dtx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.4/dtx_Linux_arm64.tar.gz"
      sha256 "4163713afb75f2d5923235fe42752320e65c0bcfeb793a8d89a0f8db2bd63c12"

      def install
        bin.install "dtx"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.4/dtx_Linux_armv6.tar.gz"
      sha256 "087cf1da8562380e9d692f844933e82250fb03e862909d8971d2eb8d96bce30f"

      def install
        bin.install "dtx"
      end
    end
  end
end
