# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtx < Formula
  desc ""
  homepage "https://github.com/rajrohanyadav/dtx"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.1/dtx_Darwin_x86_64.tar.gz"
      sha256 "1d51d5fdc1c02f720e2b6396c5daf75663cc71d3c89f057bc4f7d44a761453a4"

      def install
        bin.install "dtx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.1/dtx_Darwin_arm64.tar.gz"
      sha256 "6cdf71067a4b0e57aa022c8e7bd4ee2e39705db6969f4b49541f75252a1ce6a8"

      def install
        bin.install "dtx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.1/dtx_Linux_arm64.tar.gz"
      sha256 "da1e469300f73028b46f8c83c23a638b2342b702aa9c6f2c4ba5589662023506"

      def install
        bin.install "dtx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.1/dtx_Linux_x86_64.tar.gz"
      sha256 "1442440b99d201163628614a9d45038ab4d7ae3b06e499cb907fc7c51200de53"

      def install
        bin.install "dtx"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rajrohanyadav/dtx/releases/download/v0.0.1/dtx_Linux_armv6.tar.gz"
      sha256 "85c695b6c852458e3e58ec336db035e311f5807ae4796233ef377063004e1c94"

      def install
        bin.install "dtx"
      end
    end
  end
end
